bump_version: null
lint:
  nextflow_config: false # TMP
  schema_params: false # TMP
  actions_ci: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-smallvariants_logo_light.png
    - docs/images/nf-core-smallvariants_logo_light.png
    - docs/images/nf-core-smallvariants_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/template_version_comment.yml
    - docs/README.md
    - tests/default.nf.test
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .gitattributes
    - .prettierignore
    - LICENSE
  multiqc_config:
    - report_comment
nf_core_version: 4.0.2
repository_type: pipeline
org_path: nf-cmgg
template:
  author: nvnieuwk
  description: A nextflow pipeline for calling and annotating small variants from short DNA reads for WES and WGS data
  force: false
  is_nfcore: false
  name: smallvariants
  org: nf-cmgg
  outdir: .
  skip_features:
    - fastqc
    - is_nfcore
  version: 1.13.4dev
