repository_type: pipeline
lint:
  files_exist:
    - assets/nf-core-nfcmggstructural_logo_light.png
    - docs/images/nf-core-nfcmggstructural_logo_light.png
    - docs/images/nf-core-nfcmggstructural_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  readme:
    - nextflow_badge
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - lib/NfcoreTemplate.groovy
    - .prettierignore
  actions_ci: false
